//Union operation

1. Without using ALL Keyowrd
SELECT {COLUMN_NAME_1} FROM {TABLE1} UNION SELECT {COLUMN_NAME_1} FROM {TABLE2};

2. With using ALL Keyowrd
SELECT {COLUMN_NAME_1} FROM {TABLE1} UNION ALL SELECT {COLUMN_NAME_1} FROM {TABLE2};


// INTERSECTION

1. Without using ALL Keyowrd
SELECT {COLUMN_NAME} FROM {TABLE1} INTERSECT SELECT {COLUMN_NAME} FROM {TABLE2};

2. With using ALL Keyowrd
SELECT {COLUMN_NAME} FROM {TABLE1} INTERSECT ALL SELECT {COLUMN_NAME} FROM {TABLE2};



//SET DIFFERENCE ( MINUS / EXCEPT ) 

1. Without ALL keyword
SELECT {COLUMN_NAME} FROM {TABLE1} EXCEPT SELECT {COLUMN_NAME} FROM {TABLE2};

2. With ALL keyword
SELECT {COLUMN_NAME} FROM {TABLE1} EXCEPT ALL SELECT {COLUMN_NAME} FROM {TABLE2};
